language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  UPGRADE_OPENSSL=false
  UPGRADE_OPENSSL=true
# command to install dependencies
install:
  - pip install -r requirements.txt
  - ./maybe_upgrade_openssl.bash
# command to run tests
script:
  # Show openssl version
  - openssl version
  # Run tests
  - python tests/test_ca.py Test.test_create_ca_utf8
  - make test
notifications:
  email: false
