language: python
dist: trusty
python:
  - "3.4"
  - "3.5"
  - "3.6"
  # command to install dependencies
install:
  - pip install -r requirements.txt
  - ./ci/download_openssl.bash
# command to run tests
script:
  # Run tests
  - echo "Running tests with"
  - openssl version
  - make test
  # Run tests with openssl 1.1.0
  - echo "Running tests with openssl 1.1.0"
  - source ./ci/openssl1.1.0.bash && make test
  # Package
  - python3 setup.py bdist_egg
notifications:
  email: false
