os:
  - linux
  - osx
language: python
python:
  - "3.6"
# command to install dependencies
install:
  - python setup.py install
# command to run tests
script:
  - python setup.py test
notifications:
  email: false
